[package]
name = "MP3-Normalizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
system_shutdown = "*"
id3 = "1.7.0"
rodio = "0.17.1"
itertools = "0.10.5"
minimp3 = "0.5.1"
