[package]
name = "mp3-normalizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
system_shutdown = "4.0.1"
id3 = "1.7.0"
minimp3 = "0.5.1"
